"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Mail_1 = require("./Mail");
var Direccion_1 = require("./Direccion");
var Telefono_1 = require("./Telefono");
var Persona_1 = require("./Persona");
var personas = [];
console.log('------------- Iniciamos ejecución del programa -------------------');
var zeida = new Persona_1.Persona("Zeida", "Rodríguez Mendoza", 24, "56406618Q", "5/01/1997", "verde", "F", [], [], [], "Propio");
var reyes = new Persona_1.Persona("Reyes", "Moreno", 63, "56423418D", "3/03/1957", "verde", "M", [], [], [], "Familia");
var jonay = new Persona_1.Persona("Jonay", "Mendoza", 38, "56406348C", "14/09/1982", "azul", "F", [], [], [], "Familia");
var fayna = new Persona_1.Persona("Fayna", "Mendoza", 44, "56189218B", "09/10/1977", "rosado", "F", [], [], [], "Familia");
var luis = new Persona_1.Persona("Luis", "García", 65, "56392018A", "11/12/1954", "verde", "M", [], [], [], "Familia");
var mailzeida = new Mail_1.Mail("Personal", "Zeida@gmail.com");
zeida.addMails(mailzeida);
var mailjonay = new Mail_1.Mail("Personal", "Jonay@gmail.com");
jonay.addMails(mailjonay);
var mailreyes = new Mail_1.Mail("Personal", "Reyes@gmail.com");
reyes.addMails(mailreyes);
var mailfayna = new Mail_1.Mail("Personal", "Fayna@gmail.com");
fayna.addMails(mailfayna);
var mailluis = new Mail_1.Mail("Personal", "Luis@gmail.com");
luis.addMails(mailluis);
var direccionzeida = new Direccion_1.Direccion("Calle Venegas", "5", "3", "b", "35678", "Las Palmas", "Las Palmas");
var direccionreyes = new Direccion_1.Direccion("Calle Monanza", "10", "2", "e", "35675", "Las Palmas", "Las Palmas");
var direccionjonay = new Direccion_1.Direccion("Calle Laguna", "7", "1", "c", "35672", "Las Palmas", "Las Palmas");
var direccionfayna = new Direccion_1.Direccion("Calle La Suerte", "2", "1", "a", "32678", "Las Palmas", "Las Palmas");
var direccionluis = new Direccion_1.Direccion("Calle Troya", "6", "1", "b", "35638", "Las Palmas", "Las Palmas");
zeida.addDireccion(direccionzeida);
jonay.addDireccion(direccionjonay);
luis.addDireccion(direccionluis);
reyes.addDireccion(direccionreyes);
fayna.addDireccion(direccionfayna);
var telefonozeida = new Telefono_1.Telefono("Personal", "923867534");
var telefonoluis = new Telefono_1.Telefono("Trabajo", "986723231");
var telefonoluis2 = new Telefono_1.Telefono("Personal", "986767831");
var telefonofayna = new Telefono_1.Telefono("Personal", "876543829");
var telefonoreyes = new Telefono_1.Telefono("Casa", "987654378");
var telefonojonay = new Telefono_1.Telefono("Fijo", "389324930");
fayna.addTelefono(telefonofayna);
reyes.addTelefono(telefonoreyes);
zeida.addTelefono(telefonozeida);
jonay.addTelefono(telefonojonay);
luis.addTelefono(telefonoluis);
luis.addTelefono(telefonoluis2);
personas.push(zeida, reyes, jonay, fayna, luis);
for (var _i = 0, personas_1 = personas; _i < personas_1.length; _i++) {
    var persona = personas_1[_i];
    console.log(persona);
}
console.log('----------- Finalizamos ejecución del programa --------------------');
